# Brew
brew "cabal-install" # Haskell package manager
brew "ffmpeg" # convert video formats, frames to video, record, and stream
brew "gh" # GitHub CLI
brew "ghc" # Haskell compiler
brew "git"
brew "htop"
brew "imagemagick"
brew "mas"
brew "mysql"
brew "node"
brew "openjdk"
brew "pipx"
brew "pyenv"
brew "rustup"
brew "tmux" # terminal multiplexer
brew "tree"
brew "wget" # allow non-GUI file download from the web

# Cask
cask "anki"
cask "blender"
cask "calibre"
cask "dbeaver-community"
cask "discord"
cask "docker-desktop"
cask "figma"
cask "github"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "mactex-no-gui"
cask "microsoft-teams"
cask "miniforge"
cask "postman"
cask "quicklook-json"
cask "steam"
cask "visual-studio-code"
cask "zoom"

# Mac App Store
mas "GoodNotes", id: 1444383602
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Messenger", id: 1480068668
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Shazam", id: 897118787
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
mas "WeChat", id: 836500024
mas "WhatsApp", id: 310633997